// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AOTSerializer.Generator.Json.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class FormatterTemplate : FormatterTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("#pragma warning disable 618\r\n#pragma warning disable 612\r\n#pragma warning disable" +
                    " 414\r\n#pragma warning disable 168\r\n\r\nnamespace ");
            
            #line 11 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    using AOTSerializer.Common;\r\n    using AOTSerializer.Internal;\r\n    usin" +
                    "g AOTSerializer.Json;\r\n    using System;\r\n    using System.Linq;\r\n\r\n");
            
            #line 19 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 foreach(var objInfo in ObjectSerializationInfos) { 
            
            #line default
            #line hidden
            this.Write("\r\n    public sealed class ");
            
            #line 21 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objInfo.Name));
            
            #line default
            #line hidden
            this.Write("Formatter : FormatterBase<");
            
            #line 21 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objInfo.FullName));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        private readonly AutomataDictionary ____keyMapping;\r\n        pr" +
                    "ivate readonly byte[][] ____stringByteKeys;\r\n\r\n        public ");
            
            #line 26 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objInfo.Name));
            
            #line default
            #line hidden
            this.Write("Formatter()\r\n        {\r\n            this.____keyMapping = new AutomataDictionary(" +
                    ")\r\n            {\r\n");
            
            #line 30 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 var index = 0; foreach(var x in objInfo.Members) { 
            
            #line default
            #line hidden
            this.Write("                { System.Text.Encoding.UTF8.GetString(JsonUtility.GetEncodedPrope" +
                    "rtyNameWithoutQuotation(\"");
            
            #line 31 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.SerializationName));
            
            #line default
            #line hidden
            this.Write("\")), ");
            
            #line 31 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index++));
            
            #line default
            #line hidden
            this.Write(" },\r\n");
            
            #line 32 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            };\r\n\r\n            this.____stringByteKeys = new byte[][]\r\n           " +
                    " {\r\n");
            
            #line 37 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 index = 0; foreach(var x in objInfo.Members.Where(x => x.IsReadable)) { 
            
            #line default
            #line hidden
            
            #line 38 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if(index++ == 0) { 
            
            #line default
            #line hidden
            this.Write("                JsonUtility.GetEncodedPropertyNameWithBeginObject(\"");
            
            #line 39 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.SerializationName));
            
            #line default
            #line hidden
            this.Write("\").ToArray(),\r\n");
            
            #line 40 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                JsonUtility.GetEncodedPropertyNameWithPrefixValueSeparator(\"");
            
            #line 41 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.SerializationName));
            
            #line default
            #line hidden
            this.Write("\").ToArray(),\r\n");
            
            #line 42 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 }} 
            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n        public override void Serialize(ref byte[] by" +
                    "tes, ref int offset, ");
            
            #line 46 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objInfo.FullName));
            
            #line default
            #line hidden
            this.Write(" value, IResolver resolver)\r\n        {\r\n");
            
            #line 48 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if( objInfo.IsClass) { 
            
            #line default
            #line hidden
            this.Write("            if (value == null)\r\n            {\r\n                JsonUtility.WriteN" +
                    "ull(ref bytes, ref offset);\r\n                return;\r\n            }\r\n");
            
            #line 54 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 55 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 index = 0; foreach(var x in objInfo.Members.Where(x => x.IsReadable)) { 
            
            #line default
            #line hidden
            this.Write("            JsonUtility.WriteRaw(ref bytes, ref offset, this.____stringByteKeys[");
            
            #line 56 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index++));
            
            #line default
            #line hidden
            this.Write("]);\r\n            ");
            
            #line 57 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.SerializeMethodString));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 58 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public override ");
            
            #line 61 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objInfo.FullName));
            
            #line default
            #line hidden
            this.Write(" Deserialize(byte[] bytes, ref int offset, IResolver resolver)\r\n        {\r\n      " +
                    "      if (JsonUtility.ReadIsNull(bytes, ref offset))\r\n            {\r\n");
            
            #line 65 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if( objInfo.IsClass) { 
            
            #line default
            #line hidden
            this.Write("                return null;\r\n");
            
            #line 67 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                throw new InvalidOperationException(\"typecode is null, struct not" +
                    " supported\");\r\n");
            
            #line 69 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n");
            
            #line 72 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if( !objInfo.HasConstructor) { 
            
            #line default
            #line hidden
            this.Write("            \r\n            throw new InvalidOperationException(\"generated serializ" +
                    "er for IInterface does not support deserialize.\");\r\n");
            
            #line 74 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 76 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 foreach(var x in objInfo.Members) { 
            
            #line default
            #line hidden
            this.Write("            var __");
            
            #line 77 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__ = default(");
            
            #line 77 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.FullTypeName));
            
            #line default
            #line hidden
            this.Write(");\r\n            var __");
            
            #line 78 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__b__ = false;\r\n");
            
            #line 79 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 81 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if (objInfo.Members.FirstOrDefault(m => m.IsExtensionData) is var extensionMember && extensionMember != null) { 
            
            #line default
            #line hidden
            this.Write("            var __additionalDataDict__ = new System.Collections.Generic.Dictionar" +
                    "y<");
            
            #line 82 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(extensionMember.TypeArguments));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n");
            
            #line 84 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            JsonUtility.ReadIsBeginObjectWithVerify(bytes, ref offset);\r\n        " +
                    "    if (JsonUtility.ReadIsEndObject(bytes, ref offset))\r\n            {\r\n        " +
                    "        return new ");
            
            #line 88 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objInfo.GetConstructorString()));
            
            #line default
            #line hidden
            this.Write(@";
            }
            else
            {
                var stringKey = JsonUtility.ReadPropertyNameSegmentRaw(bytes, ref offset);
                ____keyMapping.TryGetValueSafe(stringKey, out var key);

                switch (key)
                {
");
            
            #line 97 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 index =0; foreach(var x in objInfo.Members) { 
            
            #line default
            #line hidden
            this.Write("                    case ");
            
            #line 98 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index++));
            
            #line default
            #line hidden
            this.Write(":\r\n                        __");
            
            #line 99 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__ = ");
            
            #line 99 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.DeserializeMethodString));
            
            #line default
            #line hidden
            this.Write(";\r\n                        __");
            
            #line 100 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__b__ = true;\r\n                        break;\r\n");
            
            #line 102 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 103 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if (extensionMember == null) { 
            
            #line default
            #line hidden
            this.Write("                    default:\r\n                        JsonUtility.ReadNextBlock(b" +
                    "ytes, ref offset);\r\n                        break;\r\n");
            
            #line 107 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(@"                    default:
                        var unknownData = JsonUtility.ReadNextBlockSegment(bytes, ref offset);
                        var unknownDataStr = System.Text.Encoding.UTF8.GetString(unknownData.Array, unknownData.Offset, unknownData.Count);
                        unknownDataStr = unknownDataStr.Trim();
                        if (unknownDataStr.StartsWith(""\"""") && unknownDataStr.EndsWith(""\"""")) { unknownDataStr = unknownDataStr.Substring(1, unknownDataStr.Length - 2); }
                        __additionalDataDict__.Add(System.Text.Encoding.UTF8.GetString(stringKey.Array, stringKey.Offset, stringKey.Count), unknownDataStr);
                        break;
");
            
            #line 115 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"                }
            }

            while (!JsonUtility.ReadIsEndObject(bytes, ref offset))
            {
                JsonUtility.ReadIsValueSeparatorWithVerify(bytes, ref offset);

                var stringKey = JsonUtility.ReadPropertyNameSegmentRaw(bytes, ref offset);
                ____keyMapping.TryGetValueSafe(stringKey, out var key);

                switch (key)
                {
");
            
            #line 128 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 index =0; foreach(var x in objInfo.Members) { 
            
            #line default
            #line hidden
            this.Write("                    case ");
            
            #line 129 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index++));
            
            #line default
            #line hidden
            this.Write(":\r\n                        __");
            
            #line 130 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__ = ");
            
            #line 130 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.DeserializeMethodString));
            
            #line default
            #line hidden
            this.Write(";\r\n                        __");
            
            #line 131 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__b__ = true;\r\n                        break;\r\n");
            
            #line 133 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 134 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if (extensionMember == null) { 
            
            #line default
            #line hidden
            this.Write("                    default:\r\n                        JsonUtility.ReadNextBlock(b" +
                    "ytes, ref offset);\r\n                        break;\r\n");
            
            #line 138 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(@"                    default:
                        var unknownData = JsonUtility.ReadNextBlockSegment(bytes, ref offset);
                        var unknownDataStr = System.Text.Encoding.UTF8.GetString(unknownData.Array, unknownData.Offset, unknownData.Count);
                        unknownDataStr = unknownDataStr.Trim();
                        if (unknownDataStr.StartsWith(""\"""") && unknownDataStr.EndsWith(""\"""")) { unknownDataStr = unknownDataStr.Substring(1, unknownDataStr.Length - 2); }
                        __additionalDataDict__.Add(System.Text.Encoding.UTF8.GetString(stringKey.Array, stringKey.Offset, stringKey.Count), unknownDataStr);
                        break;
");
            
            #line 146 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                }\r\n            }\r\n\r\n            var ____result = new ");
            
            #line 150 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objInfo.GetConstructorString()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 151 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 foreach(var x in objInfo.Members.Where(x => x.IsWritable)) { 
            
            #line default
            #line hidden
            this.Write("            if (__");
            
            #line 152 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__b__) ____result.");
            
            #line 152 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write(" = __");
            
            #line 152 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(x.Name));
            
            #line default
            #line hidden
            this.Write("__;\r\n");
            
            #line 153 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 155 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 if (extensionMember != null) { 
            
            #line default
            #line hidden
            this.Write("            if(!__");
            
            #line 156 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(extensionMember.Name));
            
            #line default
            #line hidden
            this.Write("__b__) ____result.");
            
            #line 156 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(extensionMember.Name));
            
            #line default
            #line hidden
            this.Write("  = __additionalDataDict__;\r\n            \r\n");
            
            #line 158 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return ____result;\r\n");
            
            #line 160 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n\r\n");
            
            #line 164 "C:\GitRepo\HoloBeam_Rearch\Submodules\AOTSerializer\generator\AOTSerializer.Generator.Json\Templates\FormatterTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n#pragma warning restore 168\r\n#pragma warning restore 414\r\n#pragma warning re" +
                    "store 618\r\n#pragma warning restore 612");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class FormatterTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
